---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fdk-reports-bff
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/updates" {
        deny all;
        return 403;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: reports-bff.demo.fellesdatakatalog.digdir.no
      http:
        paths:
          - backend:
              service:
                name: fdk-reports-bff
                port:
                  number: 8080
            path: /
            pathType: Prefix
