version: "3"
services:
  servicesmock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mock/mappings:/home/wiremock/mappings
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node