version: "3"
services:
  servicesmock:
    image: rodolpheche/wiremock
    ports:
      - "8000:8080"
    volumes:
      - ./mock/mappings:/home/wiremock/mappings
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
      - discovery.type=single-node
  fdk-reports-bff:
      image: eu.gcr.io/digdir-fdk-infra/fdk-reports-bff:test
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - servicesmock
        - elasticsearch
      environment:
        - ORGANIZATION_CATALOG_URL=http://servicesmock:8080
        - CONCEPT_HARVESTER_URL=http://servicesmock:8080
        - DATASET_HARVESTER_URL=http://servicesmock:8080
        - INFORMATIONMODELS_HARVESTER_URL=http://servicesmock:8080
        - DATASERVICE_HARVESTER_URL=http://servicesmock:8080
        - FDK_REFERENCE_DATA_URL=http://servicesmock:8080
        - DATASET_QUERY_CACHE_URL=http://servicesmock:8080
        - FDK_BASE=http://servicesmock:8080
        - SPARQL_BASE=http://servicesmock:8080
        - ELASTIC_HOST=http://elasticsearch
        - ELASTIC_PORT=9200
        - ELASTIC_TCP_PORT=9300
