openapi: 3.0.0
info:
  title: fdk-reports-bff
  version: '1.0'
  description: Backend for Frontend service that provides information about organizations and their published content in Felles Datakatalogs
  contact:
    name: Felles Datakatalog
    url: 'https://fellesdatakatalog.digdir.no/'
    email: fellesdatakatalog@digdir.no
  license:
    url: 'http://data.norge.no/nlod/no/2.0'
    name: License of API
servers:
  - url: 'http://report-bff.data.norge.no'
    description: production
  - url: 'https://report-bff.staging.fellesdatakatalog.digdir.no/'
    description: staging
paths:
  /ready:
    get:
      summary: check if application is ready to accept requests
      operationId: get-ready
      responses:
        '200':
          description: OK if service is runnning and can contact other services
        '503':
          description: Temporarily unavailable. Returned if fdk-organization-bff can not contact other services
  /ping:
    get:
      summary: ping endpoint for application fidders from ready in that is does not check if other servies are contactable
      operationId: ping
      responses:
        '200':
          description: OK if service is runnning
  '/report/{contentType}':
    get:
      operationId: getReportForContentType
      summary: endpoint for report on specific contentType
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/InformationModelsReport'
                  - $ref: '#/components/schemas/ConceptsReport'
                  - $ref: '#/components/schemas/DataSetsReport'
                  - $ref: '#/components/schemas/DataServicesReport'
    parameters:
      - schema:
          type: string
          enum:
            - datasets
            - concepts
            - informationmodels
            - dataservices
        name: contentType
        in: path
        required: true
      - in: query
        name: orgPath
        schema:
          type: string
        description: filter on fdk-org-path value
      - in: query
        name: themeprofile
        schema:
          type: string
          enum:
            - transport
        description: filter on content for themed page
      - in: query
        name: theme
        schema:
          type: string
        description: filter on los themes by fdk-los-paths
      - in: query
        name: organizationId
        schema:
          type: string
        description: filter on organizationId from national registry

  '/timeseries/{contentType}':
    get:
      operationId: getTimeSeriesReportForContentType
      summary: endpoint for timeSeries report on specific contentType
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/TimeSeriesReport'
    parameters:
      - schema:
          type: string
          enum:
            - datasets
            - concepts
            - informationmodels
            - dataservices
        name: contentType
        in: path
        required: true
      - in: query
        name: orgPath
        schema:
          type: string
        description: filter on fdk-org-path value
      - in: query
        name: themeprofile
        schema:
          type: string
          enum:
            - transport
        description: filter on content for themed page
      - in: query
        name: theme
        schema:
          type: string
        description: filter on los themes by fdk-los-paths
      - in: query
        name: organizationId
        schema:
          type: string
        description: filter on organizationId from national registry
components:
  schemas:
    Report:
      title: Report
      type: object
      properties:
        totalObjects:
          type: string
        newLastWeek:
          type: string
        catalogs:
          description: Count objects of each catalog
          type: array
          items:
            $ref: '#/components/schemas/KeyWithCountObject'
        orgPaths:
          description: Count objects for each catalog aggregated on org paths
          type: array
            items:
              $ref: '#/components/schemas/KeyWithCountObject'
        organizationCount:
          type: int
          description: Number of organizations with datasets in Felles Datakatlaog
    InformationModelsReport:
      title: InformationModelReport
      allOf:
        - $ref: '#/components/schemas/Report'
    ConceptsReport:
      title: ConceptReport
      allOf:
        - $ref: '#/components/schemas/Report'
        - type: object
          properties:
            mostInUse:
              type: array
              items:
                $ref: ''
    Reference:
      title: Reference
      type: object
      properties:
        name:
          $ref: '#/components/schemas/LanguageObject'
        uri:
          type: string
          format: uri
    LanguageObject:
      type: object
      properties:
        nb:
          type: string
        nn:
          type: string
        'no':
          type: string
        en:
          type: string
    Catalog:
      title: Organizations
      type: object
      properties:
        count:
          type: integer
        orgPath:
          type: string
    DataSetsReport:
      title: DataSetsReport
      allOf:
        - $ref: '#/components/schemas/Report'
        - type: object
          properties:
            formats:
              type: array
              items:
                $ref: '#/components/schemas/KeyWithCountObject'
            nationalComponent:
              type: number
              format: float
            opendata:
              type: number
              format: float
            withSubject:
              type: number
              format: float
            accessRights:
              type: array
              items:
                $ref: '#/components/schemas/KeyWithCountObject'
            themesAndTopicsCount:
              type: array
              items:
                $ref: '#/components/schemas/KeyWithCountObject'
    DataServicesReport:
      title: DataServiceReport
      allOf:
        - $ref: '#/components/schemas/Report'
        - properties:
            nationalComponent:
              type: number
              format: float
            openLicence:
              $ref: '#/components/schemas/PrepositionCountObject'
            openAccess:
              $ref: '#/components/schemas/PrepositionCountObject'
            freeUsage:
              $ref: '#/components/schemas/PrepositionCountObject'
            formats:
              type: array
              items:
                $ref: '#/components/schemas/KeyWithCountObject'
      description: ''
      type: object
    TimeSeriesReport:
      title: TimeSeriesReport
      properties:
        timeSeries:
          type: array
          items:
            $ref: '#/components/schemas/DataPoint'
      description: ''
      type: object
    KeyWithCountObject:
      type: object
      properties:
        key:
          type: string
        count:
          type: number
          format: float
    PrepositionCountObject:
      type: object
      properties:
        with:
          type: number
          format: float
        without:
          type: number
          format: float
    OrganizationReport:
      title: OrganizationReport
      type: object
      properties:
        orgPath:
          type: string
        name:
          $ref: '#/components/schemas/LanguageObject'
        concepts:
          $ref: '#/components/schemas/ConceptsReport'
        informationmodels:
          $ref: '#/components/schemas/InformationModelsReport'
        datasets:
          $ref: '#/components/schemas/DataSetsReport'
        dataservices:
          $ref: '#/components/schemas/DataServicesReport'
    DataPoint:
      type: object
      properties:
        xAxis:
          type: string
        yAxis:
          type: number
          format: float