[tool.poetry]
name = "fdk-reports-bff"
version = "1.0.0"
description = ""
authors = ["NilsOveTen <nils.ove.tendenes@digdir.no>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "2.1.2"
flask-cors = "3.0.10"
flask-restful = "0.3.9"
python-dotenv = "0.20.0"
requests = "2.27.1"
gunicorn = "20.1.0"
asyncstdlib = "3.10.4"
httpx = "0.23.0"
elasticsearch = "7.16.3"
apscheduler = "3.9.1"
python-dateutil = "2.8.2"
python-json-logger = "2.0.2"

[tool.poetry.dev-dependencies]
pytest = "7.1.2"
pytest-mock = "3.7.0"
mock = "4.0.3"
isort = "5.10.1"
black = "^22.3.0"
flake8 = "^4.0.1"
pep8-naming = "^0.12.1"
safety = "^1.10.3"
flake8-import-order = "^0.18.1"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.4.25"
flake8-annotations = "^2.9.0"
mypy = "^0.950"
pytest-docker = "^0.12.0"
pytest-cov = "^3.0.0"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["fdk_reports_bff"]
omit = ["*gunicorn_config.py"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
