---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fdk-reports-bff
  name: fdk-reports-bff
spec:
  selector:
    app: fdk-reports-bff
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
